name: Projekt Kodvalidering

on: 
  push: 
    branches:
      - main
  
  pull_request:
    branches:
      - main 
  

jobs:
  validate_code:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Validate syntax & Test All functions
        run: |
          # Försök kompilera hela applikationsfilen
          python -m py_compile app.py
          echo "Syntax check and compilation successful."
          
      - name: Test key application functions (GDPR & VG)
        run: |
          echo "Validera Syntax"
          python -m py_compile app.py

          echo "Initiera Databas"
          python -c "import app; app.init_db()"
          
          echo "Testa att lägga till GDPR data"
          python -c "import app; app.dis_data(); print('test är OK')

          echo "Testa att anonymisera GDPR data"
          python -c "import app; app.an_data(); print('GDPR Anonymize test OK')"

          echo "Testa GDPR-krav (cl_data)"
          python -c "import app; app.cl_data(); print('GDPR Clear test OK')"

          